apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: database
data:
    POSTGRES_USER: ENC[AES256_GCM,data:LLdTGdo8NVA=,iv:Usfgb1vj8Ltr/jcgFccD5YM6BiAYm/NwVkfiKI0wKh8=,tag:1viUKHVSkFsW+h4cHeYpeA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:lHv7iB+jpZA=,iv:isdm2dvxVWYZNFo8pwbc3Kksa9QZ896mBqzrsa4pj0Q=,tag:pj84uPECnsrL/+xjC+Mi/Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cbd3354-435500/locations/northamerica-northeast1/keyRings/my-keyring/cryptoKeys/my-key
          created_at: "2024-11-20T00:37:49Z"
          enc: CiQAOUPMt/a6lLx8khZOfEwdvCohqBMlFl5Qtpx5qOvXdzLwMKISSQDVz2qlHxhr65yi8u37YDdOpH7Php/NJ5tcsrH41Z/nArwjbjne1Cn0nXMB8m/BvHQpXCheWrA00wexBarP09vsnJzNaoYSxSY=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-20T00:37:50Z"
    mac: ENC[AES256_GCM,data:6PCf1/b239QPeUTBHDSsKmcaSiPwqf+BxKYX28jEVK2mPD9eRx9HMgFMpcvd6C2HVU3JTEzr8oCkK2X4uS1Eh47D6FOFS74hK4hWaUw8LXLx3NT42E2W1j7JkYr18Ij6Gt0svx814nFcCnWL/oSGkAZfaQsTQ08v1ILbvY2omlQ=,iv:QuBLJ8BwMA6GGmuumv5uQMvF4QtNsJdNdVRYvrIZz3w=,tag:6y+cjgVq5DLqvSZMAtz1KQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
