apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: gcr.io/cbd3354-435500/flaskapp:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: flask-config
            - secretRef:
                name: flask-secret
---
apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: flask
spec:
  selector:
    app: flask
  type: LoadBalancer  
  ports:
    - port: 5000       
      targetPort: 5000  

